[[redirects]]
  from = "/slideshow1/*"
  to = "/slideshow1"
  status = 301

[[redirects]]
  from = "/slideshow2/*"
  to = "/slideshow2"
  status = 301

[[headers]]
  for = "/version/"
  [headers.values]
    Access-Control-Allow-Origin = "*"