backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "assets/images/uploads"

#Config
site_url: https://perleyrideaudonorwall.com/
display_url: https://perleyrideaudonorwall.com/
logo_url: https://boandco.studio/images/logo.svg

#Content
collections:
  - label: "Slideshow 1"
    name: "slideshow_1"
    editor:
      preview: false
    files:
      - label: "Welcome"
        name: "welcome"
        file: "_data/slideshow_1/welcome.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", hint: "The large headline"}
          - {label: "Description", name: "description", widget: "markdown", hint: "Main content of the page"}
          - {label: "Call to action", name: "cta", widget: "string", hint: "Optional banner at the bottom of the page", required: false}
      - label: "Your Giving Matters"
        name: "donations"
        file: "_data/slideshow_1/donations.yml"
        fields:
          - label: "Your Giving Matters"
            name: "slides"
            widget: "list"
            collapsed: false
            add_to_top: true
            summary: "{{ fields.group }} - {{ fields.range }}"
            label_singular: "Slide"
            fields:
              - label: "Slide Colour"
                name: "colour"
                widget: "select"
                options:
                  - {label: "Purple", value: "purple"}
                  - {label: "Magenta", value: "magenta"}
                  - {label: "Green", value: "green"}
                hint: "Change the slides accent colour."
              - {label: "Donor Group", name: "group", widget: "string", hint: "Enter the donor group name pertaining to this level. Please us this format: Patrons / Parrains"}
              - {label: "Donor Range", name: "range", widget: "string", hint: "Enter the dollar range for the specific donor group. Please use this format: $10,000 - $25,000"}
              - {label: "Donor Names", name: "names", widget: "markdown", hint: "Enter the names of the donors, each name on its own line with a space in between."}
