backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "assets/images/uploads"

#Config
site_url: https://perleyrideaudonorwall.com/
display_url: https://perleyrideaudonorwall.com/
logo_url: https://boandco.studio/images/logo.svg

#Content
collections:
  - label: "Slideshow 1"
    name: "slideshow1"
    editor:
      preview: false
    files:
      - label: "Welcome"
        name: "welcome"
        file: "_data/slideshow1/welcome.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", hint: "The large headline"}
          - {label: "Description", name: "description", widget: "markdown", hint: "Main content of the page"}
          - {label: "Call to action", name: "cta", widget: "string", hint: "Optional banner at the bottom of the page", required: false}
      - label: "Your Giving Matters"
        name: "donations"
        file: "_data/slideshow1/donations.yml"
        fields:
          - label: "Your Giving Matters"
            name: "slides"
            widget: "list"
            collapsed: true
            add_to_top: true
            summary: "{{fields.group}} - {{fields.range}}"
            label_singular: "Slide"
            fields:
              - label: "Slide Colour"
                name: "colour"
                widget: "select"
                options:
                  - {label: "Purple", value: "purple"}
                  - {label: "Magenta", value: "magenta"}
                  - {label: "Green", value: "green"}
                hint: "Change the slides accent colour."
              - {label: "Donor Group", name: "group", widget: "string", hint: "Enter the donor group name pertaining to this level. Please us this format: Patrons / Parrains"}
              - {label: "Donor Range", name: "range", widget: "string", hint: "Enter the dollar range for the specific donor group. Please use this format: $10,000 - $25,000"}
              - {label: "Donor Names", name: "names", widget: "markdown", hint: "Enter the names of the donors, each name on its own line with a space in between."}
  - label: "Slideshow 2"
    name: "slideshow2"
    editor:
      preview: false
    files:
      - label: "Welcome"
        name: "welcome"
        file: "_data/slideshow2/welcome.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", hint: "The large headline"}
          - {label: "Description", name: "description", widget: "markdown", hint: "Main content of the page"}
          - {label: "Call to action", name: "cta", widget: "string", hint: "Optional banner at the bottom of the page", required: false}
      - label: "Upcoming events"
        name: "events"
        file: "_data/slideshow2/events.yml"
        fields:
          - label: "Events"
            name: "slides"
            widget: "list"
            collapsed: true
            add_to_top: true
            summary: "{{fields.title}} - {{fields.date}}"
            label_singular: "Event"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
                allow_multiple: false
                choose_url: false
              - {label: "Title", name: "title", widget: "string", hint: "The name of the event"}
              - {label: "Description", name: "description", widget: "markdown", hint: "A brief description of the event"}
              - {label: "Location", name: "location", widget: "string", hint: "The location of the event. (ex: Ottawa City Hall, or Online)"}
              - {label: "Event URL", name: "url", widget: "string", hint: "The URL for the event will display as a QR code"}
              - {label: "Date", name: "date", widget: "string", hint: "Enter the date(s) of the event, use 3 letter month format (ex: Mar, Apr, Aug)"}
              - {label: "Time", name: "time", widget: "string", required: false, hint: "Enter the time of the event"}
      - label: "In the news"
        name: "news"
        file: "_data/slideshow2/news.yml"
        fields:
          - label: "News"
            name: "slides"
            widget: "list"
            collapsed: true
            add_to_top: true
            summary: "{{fields.title}} - {{fields.author_name}}"
            label_singular: "News feature"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
                allow_multiple: false
                choose_url: false
              - {label: "Title", name: "title", widget: "string", hint: "Headline for the quote"}
              - {label: "Quote", name: "quote", widget: "markdown", hint: "A brief description of the event. Max 280 characters.", pattern: ['^.{0,280}$', "Can't have more than 280 characters"]}
              - {label: "Author name", name: "author_name", widget: "string", hint: "Author of the quote"}
              - {label: "Author title", name: "author_title", widget: "string", hint: "Author's job title", required: false}
              - {label: "Author company", name: "author_company", widget: "string", hint: "Author's company", required: false}
              - {label: "Call to action", name: "cta", widget: "string", hint: "Optional banner at the bottom of the page", required: false}
      - label: "Donor Updates"
        name: "features"
        file: "_data/slideshow2/features.yml"
        fields:
          - label: "Donor Updates"
            name: "slides"
            widget: "list"
            collapsed: true
            add_to_top: true
            summary: "{{fields.title}}"
            label_singular: "Update"
            fields:
              - label: "Layout"
                name: "layout"
                widget: "select"
                options:
                  - {label: "Portrait", value: "portrait"}
                  - {label: "Landscape", value: "landscape"}
              - label: "Image"
                name: "image"
                widget: "image"
                allow_multiple: false
                choose_url: false
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
